CXX=clang++
CFLAGS=-g -Wall -std=c++11 -stdlib=libc++
WildcardMatching: WildcardMatching.cpp
	$(CXX) $(CFLAGS) -o $@ $^ $(LDFLAGS)
wordBreakII: wordBreakII.cpp
	$(CXX) $(CFLAGS) -o $@ $^ $(LDFLAGS)
minimumWindowString: minimumWindowString.cpp
	$(CXX) $(CFLAGS) -o $@ $^ $(LDFLAGS)
totalHammingDistance: totalHammingDistance.cpp
	$(CXX) $(CFLAGS) -o $@ $^ $(LDFLAGS)
